#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,         tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../api/api.c"

void setMovementPower(int power, int turn){
	//turn = turn * 1.5;
	int leftBrake = 1;
	int rightBrake = 1;
	float leftFinal = (float) leftBrake * (power + turn);
	float rightFinal = (float) rightBrake * (-power + turn);

	if (abs(leftFinal) > 100)
	{
		rightFinal *= 100 / abs(leftFinal);
		leftFinal *= 100 / abs(leftFinal);
	}
	if (abs(rightFinal) > 100)
	{
		leftFinal *= 100 / abs(rightFinal);
		rightFinal *= 100 / abs(rightFinal);
	}
	motor[left] = leftFinal;
	motor[right] = rightFinal;
}

task main()
{



}
