#pragma config(Sensor, S1,     Infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     Compass,        sensorI2CHiTechnicCompass)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{



}
