#pragma config(Sensor, S1,     Infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     Compass,        sensorI2CHiTechnicCompass)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "simplemovement.c"

// Objective: Have code to make the robot move forward x feet, turn y degrees, and then move until an IR beacon is sensed

task main()
{



}
