#pragma config(Sensor, S1,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (1) {
		nxtDisplayCenteredBigTextLine(3, "%d", SensorValue[light]);
		wait10Msec(1);
	}
}
