#pragma config(Sensor, S4,     HTSMUX,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\api\Xander_Drivers\drivers\hitechnic-sensormux.h"

// Sensor MUX is connected to NXT sensor port 4 (S4)
// Port 1: Gyro
// Port 2: Sonar
// Port 3: IRSeeker
// Port 4: Touch

#include "..\api\Xander_Drivers\drivers\hitechnic-gyro.h"    //for gyro sensor
#include "..\api\Xander_Drivers\drivers\lego-ultrasound.h"    //for sonar sensor
#include "..\api\Xander_Drivers\drivers\lego-light.h"    //for light sensor
#include "..\api\Xander_Drivers\drivers\lego-touch.h"    //for touch sensor
#define gyroSensor              msensor_S4_1
#define sonarSensor             msensor_S4_2
#define lightSensor		          msensor_S4_3
#define touchSensor             msensor_S4_4

task main()
{
	HTGYROstartCal(gyroSensor);
	LSsetActive(lightSensor);
	while (nNxtButtonPressed != 0) {
		int gyroRotation = HTGYROreadRot(gyroSensor);
		int distanceInCM = USreadDist(sonarSensor);
		int raw = LSvalRaw(lightSensor);
		int nrm = LSvalNorm(lightSensor);
		bool limitSWActive = TSreadState(touchSensor);
		nxtDisplayCenteredTextLine(0, "%d", gyroRotation);
		nxtDisplayCenteredTextLine(1, "%d", distanceInCM);
		nxtDisplayCenteredTextLine(2, "%d, %d", raw, nrm);
		nxtDisplayCenteredTextLine(4, "%d", limitSWActive);
		while (nNxtButtonPressed == 3) {}
	}
	
}
