#pragma config(Sensor, S1,     gyro,       sensorHiTechnicIRSeeker600)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (nNxtButtonPressed != 0) {
		nxtDisplayCenteredBigTextLine(5, "%d", SensorValue[gyro]);
		while (nNxtButtonPressed == 3) {}
	}

}
