#pragma config(Sensor, S1,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S2,     blackAndWhite,  sensorLightInactive)
#pragma config(Sensor, S3,     color,          sensorCOLORNONE)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	string sColor;
	while (nNxtButtonPressed != 0) {
		/*switch (SensorValue[color])
    {
      case BLACKCOLOR: sColor = "Black"; break;
      case BLUECOLOR: sColor = "Blue"; break;
      case GREENCOLOR: sColor = "Green"; break;
      case YELLOWCOLOR: sColor = "Yellow"; break;
      case REDCOLOR: sColor = "Red"; break;
      case WHITECOLOR: sColor = "White"; break;
      default: sColor = "???"; break;
    }*/
		nxtDisplayCenteredBigTextLine(0, "%d", SensorValue[color]);
		nxtDisplayCenteredBigTextLine(2, "%d", SensorValue[blackAndWhite]);
		while (nNxtButtonPressed == 3) {}
	}

}
