#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftmotor_1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightmotor_1,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     trigger,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// minibot main
// version 0 (beta)

//config placeholdler
//short leftmotor_1, rightmotor_1;

#define setting_twoMotors;
#include "../api/api.c"

static int COOLDOWN_TIME = 2000;
static int TRIGGER_POWER = 50; //[0, 100]
static int TRIGGER_TIME = 100; //in milliseconds

task main()
{
	while (true) {
		getJoystickSettings(joystick);
		setMovement(correctJoystickComposite(joystick.joy1_y1), correctJoystickComposite(joystick.joy1_x2));
		if (joy1Btn(7)) {
			setMovement(0,0);
			motor[trigger] = TRIGGER_POWER;
			wait1Msec(TRIGGER_TIME);
			motor[trigger] = 0;
			wait1Msec(COOLDOWN_TIME);
		}
	}


}
