#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftmotor_1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightmotor_1,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     trigger,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// minibot main
// version 0 (beta)

//config placeholdler
//short leftmotor_1, rightmotor_1;

#define setting_twoMotors;
#include "../api/api.c"

static int COOLDOWN_TIME = 2000;
static int TRIGGER_POWER = 50; //[0, 100]
static int TRIGGER_TIME = 100; //in milliseconds

void setMovementPower2(int power, int turn){
	//turn = turn * 1.5;
	int leftBrake = 1;
	int rightBrake = 1;
	float leftFinal = (float) leftBrake * (power + turn);
	float rightFinal = (float) rightBrake * (-power + turn);

	if (abs(leftFinal) > 100)
	{
		rightFinal *= 100 / abs(leftFinal);
		leftFinal *= 100 / abs(leftFinal);
	}
	if (abs(rightFinal) > 100)
	{
		leftFinal *= 100 / abs(rightFinal);
		rightFinal *= 100 / abs(rightFinal);
	}
	if (leftFinal < 10) leftFinal = 0;
	if (rightFinal <  10) rightFinal = 0;
	motor[leftmotor_1] = leftFinal;
	motor[rightmotor_1] = rightFinal;
}

task main()
{
	/*
	motor[trigger] = 50;
	wait1Msec(1000);
	motor[trigger] = 0;
	*/
	while (true) {
	getJoystickSettings(joystick);
	setMovement(-joystick.joy1_y1, joystick.joy1_x2);
	if (joy1Btn(6)) {
		setMovement(0,0);
		motor[trigger] = TRIGGER_POWER;
		wait1Msec(TRIGGER_TIME);
		motor[trigger] = 0;
		wait1Msec(COOLDOWN_TIME);
	}
}
}
