#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftmotor_1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightmotor_1,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightmotor_2,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     grab,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     leftmotor_2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     backboard,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define setting_twoEncoders

#include "../api/api.c"

typedef enum {
	SETPOWER,
	LEFT,
	RIGHT,
	DRIVE,
	ROTATE,
	SWEEPER,
	CONVEYOR,
	BACKBOARD,
	GOALHOOK,
} Mode;

#define numModes 9

const string modeStrings[numModes] = {"Change power", "Left drive",
	"Right drive", "Parallel Drive", "Rotational Drive",
	"Sweep Motor", "Conveyor motor", "Backboard shield",
	"Goal-grabbing hook"};

Mode nextMode(Mode m);
void waitRelease(int button);
task cycleModes();

Mode currentMode = LEFT;
short power = 80;
const short powerIncrement = 5;

task main()
{
	nNxtExitClicks = 3;
	StartTask(cycleModes);
	eraseDisplay();

	while (power >= 0) {
		while (currentMode == SETPOWER) {
			while (nNxtButtonPressed == 2) {
				power -= powerIncrement;
				waitRelease(2);
			}
			while (nNxtButtonPressed == 1) {
				power += powerIncrement;
				waitRelease(1);
			}
			EndTimeSlice();
		}

		while (currentMode == LEFT) {
			if (nNxtButtonPressed == 2)
				setMovement(-power, power);
			else if (nNxtButtonPressed == 1)
				setMovement(power, power);
			else setMovement(0, 0);
			EndTimeSlice();
		}

		while (currentMode == RIGHT) {
			if (nNxtButtonPressed == 2)
				setMovement(-power, -power);
			else if (nNxtButtonPressed == 1)
				setMovement(power, -power);
			else
				setMovement(0, 0);
			EndTimeSlice();
		}

		while (currentMode == DRIVE) {
			if (nNxtButtonPressed == 2)
				setMovement(-power, 0);
			else if (nNxtButtonPressed == 1)
				setMovement(power, 0);
			else
				setMovement(0, 0);
			EndTimeSlice();
		}

		while (currentMode == ROTATE) {
			if (nNxtButtonPressed == 2)
				setMovement(0, -power);
			else if (nNxtButtonPressed == 1)
				setMovement(0, power);
			else
				setMovement(0, 0);
			EndTimeSlice();
		}

		while (currentMode == SWEEPER) {
			if (nNxtButtonPressed == 2)
				motor[sweep] = -power;
			else if (nNxtButtonPressed == 1)
				motor[sweep] = power;
			else
				motor[sweep] = 0;
			EndTimeSlice();
		}

		while (currentMode == CONVEYOR) {
			if (nNxtButtonPressed == 2)
				motor[conveyor] = -power;
			else if (nNxtButtonPressed == 1)
				motor[conveyor] = power;
			else
				motor[conveyor] = 0;
			EndTimeSlice();
		}

		while (currentMode == BACKBOARD) {
			if (nNxtButtonPressed == 2)
				disengageBackboard();
			else if (nNxtButtonPressed == 1)
				engageBackboard();
			EndTimeSlice();
		}

		while (currentMode == GOALHOOK) {
			if (nNxtButtonPressed == 2)
				releaseGoal();
			else if (nNxtButtonPressed == 1)
				grabGoal();
			EndTimeSlice();
		}
	}
}

task cycleModes() {
	while (true) {
		if (nNxtButtonPressed == 3) {
			currentMode = nextMode(currentMode);
			waitRelease(3);
		}
		if (nNxtButtonPressed == 0 && (currentMode == LEFT || currentMode == RIGHT
					|| currentMode == DRIVE || currentMode == ROTATE)) {
			resetEncoders();
		}
		else if (nNxtButtonPressed == 0) {
			StopAllTasks();
		}
		EndTimeSlice();
	}
}

Mode nextMode(Mode m) {
	if (m == SETPOWER)
		return LEFT;
	else if (m == LEFT)
		return RIGHT;
	else if (m == RIGHT)
		return DRIVE;
	else if (m == DRIVE)
		return ROTATE;
	else if (m == ROTATE)
		return SWEEPER;
	else if (m == SWEEPER)
		return CONVEYOR;
	else if (m == CONVEYOR)
		return BACKBOARD;
	else
		return SETPOWER;
}

void waitRelease(int button) {
	while (nNxtButtonPressed == button) {
		nxtDisplayCenteredTextLine(0, modeStrings[currentMode]);
		EndTimeSlice();
	}
}
