#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftmotor_1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightmotor_1,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftmotor_2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightmotor_2,  tmotorTetrix, openLoop)

// default config.c
// Contains all pragma configurations generated by robotC

// [to be generated and placed here once we have a robot]

// SUPER IMPORTANT: ONCE WE NAME MOTORS, THEY CANNOT BE CHANGED UNLESS ANY
// AND ALL CODE USING THE MOTOR CHANGES. PLEASE DO NOT CHANGE NAMES OF MOTORS
// AND SENSORS.

// If you absolutely have to change a name, you **MUST** use an automatic refactoring tool
