#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     wheel,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void setWheelPower(int cheeseburger){
	motor[wheel] = cheeseburger;
	int i = 2;
}

int

task main()
{
	while (true) {
		 getJoystickSettings(joystick);
		 int wheelPower = joystick.joy1_y1 / 1.28;
		 setWheelPower(wheelPower)
		 wait1Msec(10);
	}
}
