// default config.c
// Contains all pragma configurations generated by robotC

// [to be generated and placed here once we have a robot]

// SUPER IMPORTANT: ONCE WE NAME MOTORS, THEY CANNOT BE CHANGED UNLESS ANY
// AND ALL CODE USING THE MOTOR CHANGES. PLEASE DO NOT CHANGE NAMES OF MOTORS
// AND SENSORS.

// If you absolutely have to change a name, you **MUST** use an automatic refactoring tool