#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     infrared,              sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftmotor_1,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightmotor_1,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightmotor_2,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     grab,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     leftmotor_2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     backboard,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define setting_twoEncoders

#include "../api/Xander_Drivers/drivers/hitechnic-irseeker-v2.h"

task main()
{
	//always use ac, never use dc for the IR
	int acS1, acS2, acS3, acS4, acS5;
	HTIRS2setDSPMode(infrared, DSP_1200);
	int irValues[3] = {0, 0, 0};
	int rawIrValues[][] = {{0, 0, 0, 0, 0},{0, 0, 0, 0, 0},{0, 0, 0, 0, 0},};
	/*while (true) {
		HTIRS2readAllACStrength(infrared, acS1, acS2, acS3, acS4, acS5);
		nxtDisplayCenteredTextLine(0, "Direction: %d", HTIRS2readACDir(infrared));
		nxtDisplayCenteredTextLine(1, "Sensor 1: %d", acS1);
		nxtDisplayCenteredTextLine(2, "Sensor 2: %d", acS2);
		nxtDisplayCenteredTextLine(3, "Sensor 3: %d", acS3);
		nxtDisplayCenteredTextLine(4, "Sensor 4: %d", acS4);
		nxtDisplayCenteredTextLine(5, "Sensor 5: %d", acS5);
	}*/
	int currentPos = 1;
	while (currentPos <= 3) {
		nxtDisplayCenteredTextLine(0, "Pos: %d", currentPos);
		int placeholder = currentPos;
		while (currentPos == placeholder) {
			HTIRS2readAllACStrength(infrared, acS1, acS2, acS3, acS4, acS5);
			if (nNxtButtonPressed == 3) {
				irValues[currentPos-1] = HTIRS2readACDir(infrared);
				rawIrValues[currentPos-1][0] = acS1;
				rawIrValues[currentPos-1][1] = acS2;
				rawIrValues[currentPos-1][2] = acS3;
				rawIrValues[currentPos-1][3] = acS4;
				rawIrValues[currentPos-1][4] = acS5;
			}
			if (nNxtButtonPressed == 1)
				currentPos++;
			if (nNxtButtonPressed == 2)
				currentPos--;
		}
	}
	eraseDisplay();



}
