#warn "++--------------------------------------------------------------++"
#warn "++--------------------------------------------------------------++"
#warn "||                                                              ||"
#warn "||                         WARNING                              ||"
#warn "||     The file you have just compiled uses the api file        ||"
#warn "||       /api/coords.c This file has been renamed to be         ||"
#warn "||       /api/coordinates.c. For now, including the old         ||"
#warn "||       file will work, but please update your include         ||"
#warn "||              statements as soon as possible.                 ||"
#warn "||                                                              ||"
#warn "++--------------------------------------------------------------++"
#warn "++--------------------------------------------------------------++"

#include "coordinates.c"